; berlin cracking service
; https://intros.c64.org/main.php?module=showintro&iid=156

* = $0816
                        lda #>bitmap
                        ldy #<bitmap
                        sty $FB
                        sta $FC
                        lda #$40
                        ldy #$00
                        sty $FD
                        sta $FE
                        ldx #$24        ; bitmap on, 25 rows
                        sty $D011
copyloop                lda ($FB),y
                        sta ($FD),y
                        iny 
                        bne copyloop
                        inc $FC
                        inc $FE
                        dex 
                        bne copyloop
                        lda colorbackground
                        sta $D020
                        lda colorforeground
                        sta $D021
                        lda #$06        ; bank 1 ($4000)
                        sta $DD00
                        lda #$80        ; bitmap @ $4000, screen @ +$2000
                        sta $D018
                        lda #$d8        ; multicolor, 40 columns
                        sta $D016
                        lda colorram
fillcolourram           sta $D800,x
                        sta $D900,x
                        sta $DA00,x
                        sta $DB00,x
                        inx 
                        bne fillcolourram
                        lda #$3b
                        sta $D011
                        nop 
                        nop 
                        jmp waitkey
                        
                        .byte $80, $71, $80

bitmap                  .byte $00, $00, $00, $00, $00, $00, $00, $00
                        .byte $00, $00, $00, $00, $00, $00, $00, $00
                        .byte $00, $00, $00, $00, $00, $00, $00, $00
                        .byte $00, $00, $00, $00, $00, $00, $00, $00
                        .byte $00, $00, $00, $00, $00, $00, $00, $00
                        .byte $00, $00, $00, $00, $00, $00, $00, $00
                        .byte $00, $00, $00, $00, $00, $00, $00, $00
                        .byte $00, $00, $00, $00, $00, $00, $00, $00
                        .byte $00, $00, $00, $00, $00, $00, $00, $00
                        .byte $00, $00, $00, $00, $00, $00, $00, $00
                        .byte $00, $00, $00, $00, $00, $00, $00, $00
                        .byte $00, $00, $00, $00, $00, $00, $00, $00
                        .byte $00, $00, $00, $00, $00, $00, $00, $00
                        .byte $00, $00, $00, $00, $00, $00, $00, $00
                        .byte $00, $00, $00, $00, $00, $00, $00, $00
                        .byte $00, $00, $00, $00, $00, $00, $00, $00
                        .byte $00, $00, $00, $00, $00, $00, $00, $00
                        .byte $00, $00, $00, $00, $00, $00, $00, $00
                        .byte $00, $00, $00, $00, $00, $00, $00, $00
                        .byte $00, $00, $00, $00, $00, $00, $00, $00
                        .byte $00, $00, $00, $00, $00, $00, $00, $00
                        .byte $00, $00, $00, $00, $00, $00, $00, $00
                        .byte $00, $00, $00, $00, $00, $00, $00, $00
                        .byte $00, $00, $00, $00, $00, $00, $00, $00
                        .byte $00, $00, $00, $00, $00, $00, $00, $00
                        .byte $00, $00, $00, $00, $00, $00, $00, $00
                        .byte $00, $00, $00, $00, $00, $00, $00, $00
                        .byte $00, $00, $00, $00, $00, $00, $00, $00
                        .byte $00, $00, $00, $00, $00, $00, $00, $00
                        .byte $00, $00, $00, $00, $00, $00, $00, $00
                        .byte $00, $00, $00, $00, $00, $00, $00, $00
                        .byte $00, $00, $00, $00, $00, $00, $00, $00
                        .byte $00, $00, $00, $00, $00, $00, $00, $00
                        .byte $00, $00, $00, $00, $00, $00, $00, $00
                        .byte $00, $00, $00, $00, $00, $00, $00, $00
                        .byte $00, $00, $00, $00, $00, $00, $00, $00
                        .byte $00, $00, $00, $00, $00, $00, $00, $00
                        .byte $00, $00, $00, $00, $00, $00, $00, $00
                        .byte $00, $00, $00, $00, $00, $00, $00, $00
                        .byte $00, $00, $00, $00, $00, $00, $00, $00
                        .byte $00, $00, $00, $00, $00, $00, $00, $00
                        .byte $00, $00, $00, $00, $00, $00, $00, $00
                        .byte $00, $00, $00, $00, $00, $00, $00, $00
                        .byte $00, $00, $00, $00, $00, $00, $00, $00
                        .byte $00, $00, $00, $00, $00, $00, $00, $00
                        .byte $00, $00, $00, $00, $00, $00, $00, $00
                        .byte $00, $00, $00, $00, $00, $00, $00, $00
                        .byte $00, $00, $00, $00, $00, $00, $00, $00
                        .byte $00, $00, $00, $00, $00, $00, $00, $00
                        .byte $00, $00, $00, $00, $00, $00, $00, $00
                        .byte $00, $00, $00, $00, $00, $00, $00, $00
                        .byte $00, $00, $00, $00, $00, $00, $00, $00
                        .byte $00, $00, $00, $00, $00, $00, $00, $00
                        .byte $00, $00, $00, $00, $00, $00, $00, $00
                        .byte $00, $00, $00, $00, $00, $00, $00, $00
                        .byte $00, $00, $00, $00, $00, $00, $00, $00
                        .byte $00, $00, $00, $00, $00, $00, $00, $00
                        .byte $00, $00, $00, $00, $00, $00, $00, $00
                        .byte $00, $00, $00, $00, $00, $00, $00, $00
                        .byte $00, $00, $00, $00, $00, $00, $00, $00
                        .byte $00, $00, $00, $00, $00, $00, $00, $00
                        .byte $00, $00, $00, $00, $00, $00, $00, $00
                        .byte $00, $00, $00, $00, $00, $00, $00, $00
                        .byte $00, $00, $00, $00, $00, $00, $00, $00
                        .byte $00, $00, $00, $00, $00, $00, $00, $00
                        .byte $00, $00, $00, $00, $00, $00, $00, $00
                        .byte $00, $00, $00, $00, $00, $00, $00, $00
                        .byte $00, $00, $00, $00, $00, $00, $00, $00
                        .byte $00, $00, $00, $00, $00, $00, $00, $00
                        .byte $00, $00, $00, $00, $00, $00, $00, $00
                        .byte $00, $00, $00, $00, $00, $00, $00, $00
                        .byte $00, $00, $00, $00, $00, $00, $00, $00
                        .byte $00, $00, $00, $00, $00, $00, $00, $00
                        .byte $00, $00, $00, $00, $00, $00, $00, $00
                        .byte $00, $00, $00, $00, $00, $00, $00, $00
                        .byte $00, $00, $00, $00, $00, $00, $00, $00
                        .byte $00, $00, $00, $00, $00, $00, $00, $00
                        .byte $00, $00, $00, $00, $00, $00, $00, $00
                        .byte $00, $00, $00, $00, $00, $00, $00, $00
                        .byte $00, $00, $00, $00, $00, $00, $00, $00
                        .byte $00, $00, $00, $00, $00, $00, $00, $00
                        .byte $00, $00, $00, $00, $00, $00, $00, $00
                        .byte $00, $00, $00, $00, $00, $00, $00, $00
                        .byte $00, $00, $00, $00, $00, $00, $00, $00
                        .byte $00, $00, $00, $00, $00, $00, $00, $00
                        .byte $00, $00, $00, $00, $00, $00, $00, $00
                        .byte $00, $00, $00, $00, $00, $00, $00, $00
                        .byte $00, $00, $00, $00, $00, $00, $00, $00
                        .byte $00, $00, $00, $00, $00, $00, $00, $00
                        .byte $00, $00, $00, $00, $00, $00, $00, $00
                        .byte $00, $00, $00, $00, $00, $00, $00, $00
                        .byte $00, $00, $00, $00, $00, $00, $00, $00
                        .byte $00, $00, $00, $00, $00, $00, $00, $00
                        .byte $00, $00, $00, $00, $00, $00, $00, $00
                        .byte $00, $00, $00, $00, $00, $00, $00, $00
                        .byte $00, $00, $00, $00, $00, $00, $00, $00
                        .byte $00, $00, $00, $00, $00, $00, $00, $00
                        .byte $00, $00, $00, $00, $00, $00, $00, $00
                        .byte $00, $00, $00, $00, $00, $00, $00, $00
                        .byte $00, $00, $00, $00, $00, $00, $00, $00
                        .byte $00, $00, $00, $00, $00, $00, $00, $00
                        .byte $00, $00, $00, $00, $00, $00, $00, $00
                        .byte $00, $00, $00, $00, $00, $00, $00, $00
                        .byte $00, $00, $00, $00, $00, $00, $00, $00
                        .byte $00, $00, $00, $00, $00, $00, $00, $00
                        .byte $00, $00, $00, $00, $00, $00, $00, $00
                        .byte $00, $00, $00, $00, $00, $00, $00, $00
                        .byte $00, $00, $00, $00, $00, $00, $00, $00
                        .byte $00, $00, $00, $00, $00, $00, $00, $00
                        .byte $00, $00, $00, $00, $00, $00, $00, $00
                        .byte $00, $00, $00, $00, $00, $00, $00, $00
                        .byte $00, $00, $00, $00, $00, $00, $00, $00
                        .byte $00, $00, $00, $00, $00, $00, $00, $00
                        .byte $00, $00, $00, $00, $00, $00, $00, $00
                        .byte $00, $00, $00, $00, $00, $00, $00, $00
                        .byte $00, $00, $00, $00, $00, $00, $00, $00
                        .byte $00, $00, $00, $00, $00, $00, $00, $00
                        .byte $00, $00, $00, $00, $00, $00, $00, $00
                        .byte $00, $00, $00, $00, $00, $00, $00, $00
                        .byte $00, $00, $00, $00, $00, $00, $00, $00
                        .byte $00, $00, $00, $00, $00, $00, $aa, $ff
                        .byte $00, $00, $00, $00, $00, $00, $aa, $ff
                        .byte $00, $00, $00, $00, $00, $00, $aa, $ff
                        .byte $00, $00, $00, $00, $00, $00, $aa, $ff
                        .byte $00, $00, $00, $00, $00, $00, $aa, $ff
                        .byte $00, $00, $00, $00, $00, $00, $aa, $ff
                        .byte $00, $00, $00, $00, $00, $00, $aa, $ff
                        .byte $00, $00, $00, $00, $00, $00, $aa, $ff
                        .byte $00, $00, $00, $00, $00, $00, $aa, $ff
                        .byte $00, $00, $00, $00, $00, $00, $aa, $ff
                        .byte $00, $00, $00, $00, $00, $00, $aa, $ff
                        .byte $00, $00, $00, $00, $00, $00, $aa, $ff
                        .byte $00, $00, $00, $00, $00, $00, $aa, $ff
                        .byte $00, $00, $00, $00, $00, $00, $aa, $ff
                        .byte $00, $00, $00, $00, $00, $00, $aa, $ff
                        .byte $00, $00, $00, $00, $00, $00, $aa, $ff
                        .byte $00, $00, $00, $00, $00, $00, $aa, $ff
                        .byte $00, $00, $00, $00, $00, $00, $aa, $ff
                        .byte $00, $00, $00, $00, $00, $00, $aa, $ff
                        .byte $00, $00, $00, $00, $00, $00, $aa, $ff
                        .byte $00, $00, $00, $00, $00, $00, $aa, $ff
                        .byte $00, $00, $00, $00, $00, $00, $aa, $ff
                        .byte $00, $00, $00, $00, $00, $00, $aa, $ff
                        .byte $00, $00, $00, $00, $00, $00, $aa, $ff
                        .byte $00, $00, $00, $00, $00, $00, $aa, $ff
                        .byte $00, $00, $00, $00, $00, $00, $aa, $ff
                        .byte $00, $00, $00, $00, $00, $00, $aa, $ff
                        .byte $00, $00, $00, $00, $00, $00, $aa, $ff
                        .byte $00, $00, $00, $00, $00, $00, $aa, $ff
                        .byte $00, $00, $00, $00, $00, $00, $aa, $ff
                        .byte $00, $00, $00, $00, $00, $00, $aa, $ff
                        .byte $00, $00, $00, $00, $00, $00, $aa, $ff
                        .byte $00, $00, $00, $00, $00, $00, $aa, $ff
                        .byte $00, $00, $00, $00, $00, $00, $aa, $ff
                        .byte $00, $00, $00, $00, $00, $00, $aa, $ff
                        .byte $00, $00, $00, $00, $00, $00, $aa, $ff
                        .byte $00, $00, $00, $00, $00, $00, $aa, $ff
                        .byte $00, $00, $00, $00, $00, $00, $aa, $ff
                        .byte $00, $00, $00, $00, $00, $00, $aa, $ff
                        .byte $00, $00, $00, $00, $00, $00, $aa, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $fe
                        .byte $ae, $ff, $be, $ff, $ad, $d5, $55, $55
                        .byte $ae, $ff, $aa, $fe, $5d, $56, $55, $55
                        .byte $ae, $ff, $aa, $ff, $ae, $6e, $6a, $5a
                        .byte $ae, $ff, $aa, $ea, $aa, $be, $ba, $fb
                        .byte $ae, $ff, $be, $bf, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $ae, $ef, $ae, $ef, $ae, $ef
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $f5, $b5, $fd, $ae, $de, $96, $d5
                        .byte $a9, $55, $55, $55, $55, $d5, $ae, $55
                        .byte $5d, $5d, $55, $55, $55, $55, $55, $55
                        .byte $55, $55, $55, $55, $55, $55, $55, $55
                        .byte $56, $5a, $56, $57, $56, $5b, $56, $57
                        .byte $aa, $fb, $aa, $ff, $ae, $bf, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $bf, $ae, $bf, $be, $bf
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ef, $ae, $ef, $ae, $ed, $a5, $d5
                        .byte $ae, $ff, $be, $ff, $ae, $55, $55, $55
                        .byte $ae, $ff, $be, $ff, $ae, $bf, $7e, $7f
                        .byte $a6, $f9, $b5, $fe, $ae, $fe, $be, $ff
                        .byte $ae, $55, $55, $ee, $aa, $b5, $a5, $95
                        .byte $55, $55, $55, $55, $55, $55, $55, $55
                        .byte $55, $55, $55, $55, $55, $55, $55, $55
                        .byte $56, $57, $56, $56, $56, $5a, $56, $5a
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $bf
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $bf, $be, $bf, $ae, $bf, $be, $bf
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $a5, $d5, $a5, $ed, $ae, $ef, $ae, $ef
                        .byte $55, $55, $55, $e5, $a5, $ef, $ae, $ef
                        .byte $5e, $55, $55, $55, $55, $55, $55, $d5
                        .byte $ae, $6a, $7e, $5f, $55, $55, $55, $55
                        .byte $95, $95, $55, $55, $55, $55, $55, $55
                        .byte $55, $55, $55, $55, $55, $55, $55, $55
                        .byte $55, $55, $55, $55, $55, $55, $55, $55
                        .byte $5a, $5a, $56, $5b, $56, $57, $56, $5b
                        .byte $ae, $af, $aa, $ab, $aa, $aa, $ba, $ba
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $af
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $bf, $be, $bf, $ae, $bf, $be, $bf
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ef, $ae, $ef, $a5, $e5, $95, $e5
                        .byte $ae, $ef, $ae, $ef, $6e, $57, $55, $55
                        .byte $55, $ff, $be, $ff, $ae, $a9, $55, $55
                        .byte $55, $f5, $b5, $f5, $55, $55, $55, $55
                        .byte $55, $55, $55, $55, $55, $55, $55, $55
                        .byte $55, $55, $55, $55, $55, $55, $55, $55
                        .byte $55, $55, $55, $55, $55, $55, $55, $55
                        .byte $6a, $6b, $5a, $6b, $6a, $6b, $6a, $6b
                        .byte $aa, $be, $be, $be, $ae, $be, $ba, $bf
                        .byte $ae, $af, $ae, $af, $ae, $ae, $ae, $ae
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $bf, $be, $bf, $ae, $bf, $be, $bf
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $9d, $e5, $ae, $ef, $ae, $ef, $ae, $ef
                        .byte $55, $55, $55, $d5, $a5, $ff, $be, $ff
                        .byte $55, $55, $55, $55, $5e, $7f, $be, $ff
                        .byte $55, $55, $55, $55, $65, $f5, $b5, $fd
                        .byte $55, $55, $55, $55, $55, $55, $55, $55
                        .byte $55, $55, $55, $55, $55, $55, $55, $55
                        .byte $55, $55, $55, $55, $55, $55, $55, $55
                        .byte $56, $5b, $56, $5b, $56, $5b, $56, $57
                        .byte $ae, $bf, $be, $bf, $ae, $bf, $be, $be
                        .byte $ae, $ae, $aa, $aa, $aa, $aa, $aa, $aa
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $bf, $be, $bf, $ae, $bf, $be, $bf
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ef, $ae, $ef, $ae, $ef, $ae, $ef
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ad, $f5, $b5, $d5
                        .byte $55, $55, $55, $55, $55, $55, $55, $55
                        .byte $55, $55, $55, $55, $55, $55, $55, $55
                        .byte $55, $55, $55, $55, $55, $55, $55, $55
                        .byte $5e, $5f, $56, $5f, $56, $57, $56, $57
                        .byte $ae, $be, $be, $be, $ae, $be, $ba, $ae
                        .byte $aa, $aa, $aa, $aa, $aa, $aa, $aa, $aa
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $bf, $be, $bf, $ae, $bf, $be, $bf
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ef, $ae, $ef, $ae, $ef, $ae, $ef
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $fd, $a5, $e5, $95, $e5
                        .byte $55, $55, $55, $55, $55, $55, $55, $55
                        .byte $55, $55, $55, $57, $56, $57, $56, $57
                        .byte $55, $55, $75, $fd, $ad, $fa, $ba, $eb
                        .byte $55, $55, $55, $55, $55, $55, $55, $55
                        .byte $55, $55, $55, $55, $55, $55, $55, $55
                        .byte $6e, $ae, $6e, $6e, $6e, $6e, $6e, $6a
                        .byte $aa, $aa, $aa, $ea, $aa, $ea, $aa, $ea
                        .byte $ae, $ff, $be, $bf, $ae, $bf, $be, $bf
                        .byte $ae, $bf, $be, $bf, $ae, $bf, $be, $bf
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ef, $ae, $ef, $ae, $ef, $ae, $ef
                        .byte $ae, $fe, $be, $fe, $ae, $ff, $be, $ff
                        .byte $95, $a5, $a5, $95, $95, $f5, $95, $d5
                        .byte $55, $55, $55, $55, $55, $55, $55, $56
                        .byte $56, $5a, $6a, $6a, $6a, $aa, $aa, $aa
                        .byte $aa, $fb, $aa, $af, $aa, $bb, $ae, $bf
                        .byte $55, $d5, $75, $d5, $55, $d5, $75, $d5
                        .byte $55, $55, $55, $55, $55, $55, $55, $55
                        .byte $6a, $aa, $6a, $aa, $6a, $6a, $6a, $aa
                        .byte $aa, $ea, $aa, $aa, $aa, $aa, $aa, $ea
                        .byte $ae, $af, $ae, $af, $ae, $af, $ae, $ae
                        .byte $ae, $bf, $be, $bf, $aa, $af, $ba, $af
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ef, $ae, $ef, $ad, $e5, $a5, $d5
                        .byte $ae, $ff, $be, $ff, $ae, $5d, $55, $55
                        .byte $95, $d5, $95, $55, $55, $55, $55, $55
                        .byte $55, $56, $56, $5e, $5e, $5e, $56, $5a
                        .byte $aa, $aa, $ae, $af, $ae, $af, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $bd, $f5
                        .byte $55, $d5, $75, $d5, $95, $55, $55, $55
                        .byte $56, $56, $55, $57, $55, $55, $56, $57
                        .byte $aa, $aa, $aa, $aa, $6a, $aa, $aa, $aa
                        .byte $aa, $ea, $aa, $ea, $aa, $aa, $aa, $ea
                        .byte $aa, $aa, $aa, $af, $aa, $ae, $ae, $ae
                        .byte $ae, $bf, $be, $bf, $ae, $bb, $be, $bf
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $bf
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $bf, $be, $bf
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $a5, $e5, $ad, $ef, $ae, $ef, $ae, $ef
                        .byte $55, $55, $55, $55, $95, $f5, $be, $ff
                        .byte $55, $55, $55, $57, $5e, $7f, $be, $ff
                        .byte $5e, $7f, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $95, $d5, $55, $55, $95, $ff, $be, $ff
                        .byte $55, $55, $55, $55, $65, $aa, $aa, $ff
                        .byte $56, $5a, $6a, $aa, $6a, $aa, $ae, $af
                        .byte $aa, $aa, $aa, $aa, $aa, $aa, $aa, $ea
                        .byte $aa, $aa, $aa, $aa, $aa, $aa, $aa, $eb
                        .byte $aa, $ab, $aa, $ab, $aa, $aa, $ae, $bf
                        .byte $ae, $bf, $ae, $bf, $ae, $bf, $be, $bf
                        .byte $ae, $fa, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ab, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $af, $be, $ff, $ae, $ff, $be, $ff
                        .byte $aa, $eb, $aa, $ef, $ae, $ff, $be, $ff
                        .byte $aa, $eb, $aa, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $bf, $be, $bf, $ae, $bf, $be, $fe
                        .byte $ae, $fe, $ba, $ea, $aa, $ea, $aa, $aa
                        .byte $aa, $af, $ae, $af, $ae, $af, $ae, $af
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $fb, $aa, $fa, $ba, $ee
                        .byte $aa, $aa, $aa, $aa, $aa, $aa, $aa, $aa
                        .byte $aa, $aa, $ae, $aa, $aa, $aa, $aa, $aa
                        .byte $ae, $af, $ae, $ef, $aa, $aa, $aa, $aa
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $aa, $ae
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $80, $cb
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $3e, $3f
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $b8, $f8
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $bc, $f3
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $02, $fc
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $3e, $3f
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $fe, $be, $ff
                        .byte $ae, $fe, $ba, $ea, $aa, $aa, $aa, $aa
                        .byte $aa, $ea, $aa, $aa, $aa, $aa, $aa, $aa
                        .byte $aa, $aa, $aa, $aa, $aa, $aa, $80, $2a
                        .byte $aa, $aa, $aa, $aa, $aa, $aa, $aa, $2a
                        .byte $aa, $aa, $aa, $aa, $aa, $aa, $aa, $aa
                        .byte $ae, $aa, $aa, $aa, $aa, $aa, $aa, $aa
                        .byte $ae, $bf, $be, $bf, $ae, $aa, $aa, $aa
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $ba, $aa
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $aa
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $8e, $cf, $8e, $cf, $80, $cf, $8e, $cf
                        .byte $2e, $2f, $3e, $3f, $0e, $cf, $8e, $cf
                        .byte $ae, $ff, $be, $ff, $ae, $03, $32, $03
                        .byte $ae, $ff, $be, $ff, $ae, $e0, $8e, $cf
                        .byte $a8, $f8, $b8, $f8, $a8, $f8, $38, $f8
                        .byte $ae, $ff, $be, $fc, $ae, $fc, $bc, $fc
                        .byte $ae, $ff, $be, $ff, $ae, $f0, $b2, $f3
                        .byte $ae, $ff, $be, $ff, $ae, $2f, $8e, $cf
                        .byte $a2, $f3, $b2, $f3, $a2, $f3, $b2, $f3
                        .byte $ac, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $fc, $b2, $f3
                        .byte $ae, $ff, $be, $ff, $ae, $2f, $8a, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $80, $28, $3c
                        .byte $ae, $ff, $be, $ff, $ae, $fc, $b2, $f3
                        .byte $ae, $ff, $be, $ff, $ae, $3f, $8a, $ef
                        .byte $2e, $3f, $3e, $3f, $2c, $32, $0a, $0b
                        .byte $aa, $ef, $a8, $aa, $ae, $bc, $bc, $fc
                        .byte $ae, $bf, $be, $ff, $ae, $f0, $b2, $f3
                        .byte $ae, $ff, $be, $ff, $ae, $3f, $8e, $cf
                        .byte $aa, $aa, $aa, $fa, $ae, $c2, $3c, $3c
                        .byte $aa, $aa, $aa, $aa, $aa, $aa, $aa, $aa
                        .byte $2a, $2a, $2a, $2a, $2a, $80, $aa, $aa
                        .byte $2a, $aa, $aa, $aa, $aa, $a8, $28, $28
                        .byte $aa, $aa, $aa, $aa, $aa, $0a, $8a, $0a
                        .byte $aa, $aa, $aa, $aa, $aa, $82, $38, $2a
                        .byte $aa, $ab, $aa, $ab, $ae, $f3, $b2, $b2
                        .byte $aa, $ff, $be, $ff, $ae, $f3, $b2, $b3
                        .byte $ae, $ff, $8e, $ef, $ae, $cf, $8e, $cf
                        .byte $ae, $ff, $be, $ff, $ae, $c3, $3c, $3f
                        .byte $ae, $ff, $be, $ff, $ae, $f0, $b2, $f0
                        .byte $ae, $ff, $be, $ff, $ae, $3f, $3e, $3f
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ad, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $66, $77, $76, $77
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $8e, $cf, $8e, $cf, $80, $ff, $be, $ff
                        .byte $8e, $cf, $8e, $cf, $0e, $ff, $be, $ff
                        .byte $2e, $3f, $3e, $3f, $02, $ff, $be, $ff
                        .byte $8e, $cf, $8e, $cf, $8e, $ff, $be, $ff
                        .byte $a8, $f8, $b8, $f8, $a8, $fb, $be, $ff
                        .byte $ac, $fc, $bc, $fc, $2c, $ff, $be, $ff
                        .byte $a2, $f3, $b2, $f3, $a2, $ff, $be, $ff
                        .byte $8e, $cf, $8e, $cf, $8e, $ff, $be, $ff
                        .byte $a2, $f3, $b2, $f3, $a8, $ff, $be, $ff
                        .byte $ae, $ff, $bc, $fc, $02, $ff, $be, $ff
                        .byte $a2, $f3, $b2, $f3, $a2, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $2c, $3c, $3c, $3c, $80, $ff, $be, $ff
                        .byte $a2, $f3, $b2, $f3, $ac, $ff, $be, $ff
                        .byte $ae, $ff, $be, $cf, $2e, $ff, $be, $ff
                        .byte $0e, $23, $38, $3e, $2e, $ff, $be, $ff
                        .byte $ac, $fc, $bc, $3c, $2c, $ff, $be, $ff
                        .byte $a2, $f3, $b2, $f3, $a2, $ff, $be, $ff
                        .byte $8e, $cf, $8e, $cf, $8e, $ff, $be, $ff
                        .byte $2c, $3c, $3c, $3c, $80, $fc, $bc, $fc
                        .byte $aa, $fa, $be, $ff, $ae, $ff, $be, $ff
                        .byte $aa, $aa, $3a, $3a, $80, $fe, $be, $fe
                        .byte $28, $28, $28, $28, $a8, $ab, $be, $ff
                        .byte $aa, $ab, $aa, $af, $0a, $ff, $be, $ff
                        .byte $2e, $3f, $3e, $3f, $2e, $ff, $be, $ff
                        .byte $a2, $f0, $b8, $fb, $aa, $ff, $be, $ff
                        .byte $a2, $c3, $8a, $3b, $2a, $ff, $be, $ff
                        .byte $8e, $cf, $8e, $cf, $8e, $ff, $be, $ff
                        .byte $2e, $3f, $3e, $3c, $82, $ff, $be, $ff
                        .byte $a2, $f3, $b2, $f3, $a0, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $2e, $ff, $be, $ff
                        .byte $ae, $ff, $bc, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $0c, $3c, $2c, $3c, $be, $ff
                        .byte $ae, $ff, $8e, $0f, $8e, $cf, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ae, $ff, $be, $ff, $ae, $ff, $be, $ff
                        .byte $ad, $ff, $be, $ff, $ae, $00, $00, $00
                        .byte $a5, $ff, $be, $ff, $ae, $00, $00, $00
                        .byte $ae, $ff, $be, $ff, $ae, $00, $00, $00
                        .byte $ae, $ff, $be, $ff, $ae, $00, $00, $00
                        .byte $ae, $ff, $be, $ff, $ae, $00, $00, $00
                        .byte $ae, $ff, $be, $ff, $ae, $00, $00, $00
                        .byte $ae, $ff, $be, $ff, $ae, $00, $00, $00
                        .byte $ae, $ff, $be, $ff, $ae, $00, $00, $00
                        .byte $ae, $ff, $be, $ff, $ae, $00, $00, $00
                        .byte $ae, $ff, $be, $ff, $ae, $00, $00, $00
                        .byte $ae, $ff, $be, $ff, $ae, $00, $00, $00
                        .byte $ae, $ff, $be, $ff, $ae, $00, $00, $00
                        .byte $ae, $ff, $be, $ff, $ae, $00, $00, $00
                        .byte $ae, $ff, $be, $ff, $ae, $00, $00, $00
                        .byte $ae, $ff, $be, $ff, $ae, $00, $00, $00
                        .byte $ae, $ff, $be, $ff, $ae, $00, $00, $00
                        .byte $ae, $ff, $be, $ff, $ae, $00, $00, $00
                        .byte $ae, $ff, $be, $ff, $ae, $00, $00, $00
                        .byte $ae, $ff, $be, $ff, $ae, $00, $00, $00
                        .byte $ae, $ff, $be, $ff, $ae, $00, $00, $00
                        .byte $ae, $ff, $be, $ff, $ae, $00, $00, $00
                        .byte $ae, $ff, $be, $ff, $ae, $00, $00, $00
                        .byte $2c, $c3, $be, $ff, $ae, $00, $00, $00
                        .byte $ae, $ff, $be, $ff, $ae, $00, $00, $00
                        .byte $ae, $ff, $be, $ff, $ae, $00, $00, $00
                        .byte $ae, $ff, $be, $ff, $ae, $00, $00, $00
                        .byte $ae, $ff, $be, $ff, $ae, $00, $00, $00
                        .byte $ae, $ff, $be, $ff, $ae, $00, $00, $00
                        .byte $ae, $ff, $be, $ff, $ae, $00, $00, $00
                        .byte $ae, $ff, $be, $ff, $ae, $00, $00, $00
                        .byte $ae, $ff, $be, $ff, $ae, $00, $00, $00
                        .byte $ae, $ff, $be, $ff, $ae, $00, $00, $00
                        .byte $ae, $ff, $be, $ff, $ae, $00, $00, $00
                        .byte $ae, $ff, $be, $ff, $ae, $00, $00, $00
                        .byte $ae, $ff, $be, $ff, $ae, $00, $00, $00
                        .byte $ae, $ff, $be, $ff, $ae, $00, $00, $00
                        .byte $ae, $ff, $be, $ff, $ae, $00, $00, $00
                        .byte $ae, $ff, $be, $ff, $ae, $00, $00, $00
                        .byte $ae, $ff, $be, $ff, $ae, $00, $00, $00
                        .byte $ae, $ff, $be, $ff, $ae, $00, $00, $00
                        .byte $00, $00, $00, $00, $00, $00, $00, $00
                        .byte $00, $00, $00, $00, $00, $00, $00, $00
                        .byte $00, $00, $00, $00, $00, $00, $00, $00
                        .byte $00, $00, $00, $00, $00, $00, $00, $00
                        .byte $00, $00, $00, $00, $00, $00, $00, $00
                        .byte $00, $00, $00, $00, $00, $00, $00, $00
                        .byte $00, $00, $00, $00, $00, $00, $00, $00
                        .byte $00, $00, $00, $00, $00, $00, $00, $00
                        .byte $00, $00, $00, $00, $00, $00, $00, $00
                        .byte $00, $00, $00, $00, $00, $00, $00, $00
                        .byte $00, $00, $00, $00, $00, $00, $00, $00
                        .byte $00, $00, $00, $00, $00, $00, $00, $00
                        .byte $00, $00, $00, $00, $00, $00, $00, $00
                        .byte $00, $00, $00, $00, $00, $00, $00, $00
                        .byte $00, $00, $00, $00, $00, $00, $00, $00
                        .byte $00, $00, $00, $00, $00, $00, $00, $00
                        .byte $00, $00, $00, $00, $00, $00, $00, $00
                        .byte $00, $00, $00, $00, $00, $00, $00, $00
                        .byte $00, $00, $00, $00, $00, $00, $00, $00
                        .byte $00, $00, $00, $00, $00, $00, $00, $00
                        .byte $00, $00, $00, $00, $00, $00, $00, $00
                        .byte $00, $00, $00, $00, $00, $00, $00, $00
                        .byte $00, $00, $00, $00, $00, $00, $00, $00
                        .byte $00, $00, $00, $00, $00, $00, $00, $00
                        .byte $00, $00, $00, $00, $00, $00, $00, $00
                        .byte $00, $00, $00, $00, $00, $00, $00, $00
                        .byte $00, $00, $00, $00, $00, $00, $00, $00
                        .byte $00, $00, $00, $00, $00, $00, $00, $00
                        .byte $00, $00, $00, $00, $00, $00, $00, $00
                        .byte $00, $00, $00, $00, $00, $00, $00, $00
                        .byte $00, $00, $00, $00, $00, $00, $00, $00
                        .byte $00, $00, $00, $00, $00, $00, $00, $00
                        .byte $00, $00, $00, $00, $00, $00, $00, $00
                        .byte $00, $00, $00, $00, $00, $00, $00, $00
                        .byte $00, $00, $00, $00, $00, $00, $00, $00
                        .byte $00, $00, $00, $00, $00, $00, $00, $00
                        .byte $00, $00, $00, $00, $00, $00, $00, $00
                        .byte $00, $00, $00, $00, $00, $00, $00, $00
                        .byte $00, $00, $00, $00, $00, $00, $00, $00
                        .byte $00, $00, $00, $00, $00, $00, $00, $00
                        .byte $00, $00, $00, $00, $00, $00, $00, $00
                        .byte $00, $00, $00, $00, $00, $00, $00, $00
                        .byte $00, $00, $00, $00, $00, $00, $00, $00
                        .byte $00, $00, $00, $00, $00, $00, $00, $00
                        .byte $00, $00, $00, $00, $00, $00, $00, $00
                        .byte $00, $00, $00, $00, $00, $00, $00, $00
                        .byte $00, $00, $00, $00, $00, $00, $00, $00
                        .byte $00, $00, $00, $00, $00, $00, $00, $00
                        .byte $00, $00, $00, $00, $00, $00, $00, $00
                        .byte $00, $00, $00, $00, $00, $00, $00, $00
                        .byte $00, $00, $00, $00, $00, $00, $00, $00
                        .byte $00, $00, $00, $00, $00, $00, $00, $00
                        .byte $00, $00, $00, $00, $00, $00, $00, $00
                        .byte $00, $00, $00, $00, $00, $00, $00, $00
                        .byte $00, $00, $00, $00, $00, $00, $00, $00
                        .byte $00, $00, $00, $00, $00, $00, $00, $00
                        .byte $00, $00, $00, $00, $00, $00, $00, $00
                        .byte $00, $00, $00, $00, $00, $00, $00, $00
                        .byte $00, $00, $00, $00, $00, $00, $00, $00
                        .byte $00, $00, $00, $00, $00, $00, $00, $00
                        .byte $00, $00, $00, $00, $00, $00, $00, $00
                        .byte $00, $00, $00, $00, $00, $00, $00, $00
                        .byte $00, $00, $00, $00, $00, $00, $00, $00
                        .byte $00, $00, $00, $00, $00, $00, $00, $00
                        .byte $00, $00, $00, $00, $00, $00, $00, $00
                        .byte $00, $00, $00, $00, $00, $00, $00, $00
                        .byte $00, $00, $00, $00, $00, $00, $00, $00
                        .byte $00, $00, $00, $00, $00, $00, $00, $00
                        .byte $00, $00, $00, $00, $00, $00, $00, $00
                        .byte $00, $00, $00, $00, $00, $00, $00, $00
                        .byte $00, $00, $00, $00, $00, $00, $00, $00
                        .byte $00, $00, $00, $00, $00, $00, $00, $00
                        .byte $00, $00, $00, $00, $00, $00, $00, $00
                        .byte $00, $00, $00, $00, $00, $00, $00, $00
                        .byte $00, $00, $00, $00, $00, $00, $00, $00
                        .byte $00, $00, $00, $00, $00, $00, $00, $00
                        .byte $00, $00, $00, $00, $00, $00, $00, $00
                        .byte $00, $00, $00, $00, $00, $00, $00, $00
                        .byte $00, $00, $00, $00, $00, $00, $00, $00
                        .byte $00, $00, $00, $00, $00, $00, $00, $00
                        .byte $00, $00, $00, $00, $00, $00, $00, $00
                        .byte $00, $00, $00, $00, $00, $00, $00, $00
                        .byte $00, $00, $00, $00, $00, $00, $00, $00
                        .byte $00, $00, $00, $00, $00, $00, $00, $00
                        .byte $00, $00, $00, $00, $00, $00, $00, $00
                        .byte $00, $00, $00, $00, $00, $00, $00, $00
                        .byte $00, $00, $00, $00, $00, $00, $00, $00
                        .byte $00, $00, $00, $00, $00, $00, $00, $00
                        .byte $00, $00, $00, $00, $00, $00, $00, $00
                        .byte $00, $00, $00, $00, $00, $00, $00, $00
                        .byte $00, $00, $00, $00, $00, $00, $00, $00
                        .byte $00, $00, $00, $00, $00, $00, $00, $00
                        .byte $00, $00, $00, $00, $00, $00, $00, $00
                        .byte $00, $00, $00, $00, $00, $00, $00, $00
                        .byte $00, $00, $00, $00, $00, $00, $00, $00
                        .byte $00, $00, $00, $00, $00, $00, $00, $00
                        .byte $00, $00, $00, $00, $00, $00, $00, $00
                        .byte $00, $00, $00, $00, $00, $00, $00, $00
                        .byte $00, $00, $00, $00, $00, $00, $00, $00
                        .byte $00, $00, $00, $00, $00, $00, $00, $00
                        .byte $00, $00, $00, $00, $00, $00, $00, $00
                        .byte $00, $00, $00, $00, $00, $00, $00, $00
                        .byte $00, $00, $00, $00, $00, $00, $00, $00
                        .byte $00, $00, $00, $00, $00, $00, $00, $00
                        .byte $00, $00, $00, $00, $00, $00, $00, $00
                        .byte $00, $00, $00, $00, $00, $00, $00, $00
                        .byte $00, $00, $00, $00, $00, $00, $00, $00
                        .byte $00, $00, $00, $00, $00, $00, $00, $00
                        .byte $00, $00, $00, $00, $00, $00, $00, $00
                        .byte $00, $00, $00, $00, $00, $00, $00, $00
                        .byte $00, $00, $00, $00, $00, $00, $00, $00
                        .byte $00, $00, $00, $00, $00, $00, $00, $00
                        .byte $00, $00, $00, $00, $00, $00, $00, $00
                        .byte $00, $00, $00, $00, $00, $00, $00, $00
                        .byte $00, $00, $00, $00, $00, $00, $00, $00
                        .byte $00, $00, $00, $00, $00, $00, $00, $00
                        .byte $00, $00, $00, $00, $00, $00, $00, $00
                        .byte $00, $00, $00, $00, $00, $00, $00, $00
                        .byte $00, $00, $00, $00, $00, $00, $00, $00
                        .byte $00, $00, $00, $00, $00, $00, $00, $00    ; bitmap ends
                        
                        .byte $02, $0b, $01, $01, $00, $ae, $ff, $be    ; char ram
                        .byte $ff, $00, $00, $00, $00, $55, $55, $55
                        .byte $55, $00, $51, $11, $15, $00, $ff, $00
                        .byte $ff, $00, $00, $00, $00, $00, $00, $00
                        .byte $00, $00, $00, $00, $00, $00, $00, $00
                        .byte $00, $00, $00, $00, $00, $00, $00, $00
                        .byte $00, $00, $00, $00, $00, $00, $00, $00
                        .byte $00, $00, $00, $00, $00, $00, $00, $00
                        .byte $00, $00, $ff, $00, $ff, $ff, $ff, $ff
                        .byte $ff, $ff, $ff, $ff, $ff, $ff, $14, $08
                        .byte $d1, $07, $9e, $32, $30, $37, $30, $14
                        .byte $14, $30, $31, $20, $4a, $45, $44, $49
                        .byte $00, $00, $00, $a9, $08, $a0, $73, $84
                        .byte $fb, $85, $fc, $a9, $40, $a0, $00, $84
                        .byte $fd, $85, $fe, $a2, $24, $8c, $11, $d0
                        .byte $b1, $fb, $91, $fd, $c8, $d0, $f9, $e6
                        .byte $fc, $e6, $fe, $ca, $d0, $f2, $ad, $44
                        .byte $5f, $8d, $20, $d0, $ad, $40, $5f, $8d
                        .byte $21, $d0, $a9, $06, $8d, $00, $dd, $a9
                        .byte $80, $8d, $18, $d0, $a9, $d8, $8d, $16
                        .byte $d0, $ad, $43, $5f, $9d, $00, $d8, $9d
                        .byte $00, $d9, $9d, $00, $da, $9d, $00, $db
                        .byte $e8, $d0, $f1, $a9, $3b, $8d, $11, $d0
                        .byte $d0, $fe, $48, $81, $71, $80, $71, $80
                        .byte $b1, $b1, $b1, $b1, $b1, $b1, $b1, $b1
                        .byte $b1, $b1, $b1, $b1, $b1, $b1, $b1, $b1
                        .byte $b1, $b1, $b1, $b1, $b1, $b1, $b1, $b1
                        .byte $b1, $b1, $b1, $b1, $b1, $b1, $b1, $b1
                        .byte $b1, $b1, $b1, $b1, $b1, $b1, $b1, $b1
                        .byte $b1, $b1, $b1, $b1, $b1, $b1, $b1, $b1
                        .byte $b1, $b1, $b1, $b1, $b1, $b1, $b1, $b1
                        .byte $b1, $b1, $b1, $b1, $b1, $b1, $b1, $b1
                        .byte $b1, $b1, $b1, $b1, $b1, $b1, $b1, $b1
                        .byte $b1, $b1, $b1, $b1, $b1, $b1, $b1, $b1
                        .byte $b1, $b1, $b1, $b1, $b1, $b1, $b1, $b1
                        .byte $b1, $b1, $b1, $b1, $b1, $b1, $b1, $b1
                        .byte $b1, $b1, $b1, $b1, $b1, $b1, $b1, $b1
                        .byte $b1, $b1, $b1, $b1, $b1, $b1, $b1, $b1
                        .byte $b1, $b1, $b1, $b1, $b1, $b1, $b1, $b1
                        .byte $b1, $b1, $b1, $b1, $b1, $b1, $b1, $b1
                        .byte $b1, $b1, $b1, $b1, $b1, $b1, $b1, $b1
                        .byte $b1, $b1, $b1, $b1, $b1, $b1, $b1, $b1
                        .byte $b1, $b1, $b1, $b1, $b1, $b1, $b1, $b1
                        .byte $b1, $b1, $b1, $b1, $b1, $b1, $b1, $b1
                        .byte $b1, $b1, $b1, $b1, $b1, $b1, $b1, $b1
                        .byte $b1, $b1, $b1, $b1, $b1, $b1, $b1, $b1
                        .byte $b1, $b1, $b1, $b1, $b1, $b1, $b1, $b1
                        .byte $b1, $b1, $b1, $b1, $b1, $b1, $b1, $b1
                        .byte $b1, $b1, $b1, $b1, $b1, $b1, $b1, $b1
                        .byte $b1, $b1, $b1, $b1, $b1, $b1, $b1, $b1
                        .byte $b1, $b1, $b1, $b1, $b1, $b1, $b1, $b1
                        .byte $b1, $b1, $b1, $b1, $b1, $b1, $b1, $b1
                        .byte $b1, $b1, $b1, $b1, $b1, $b1, $b1, $b1
                        .byte $b1, $b1, $b1, $b1, $b1, $b1, $b1, $b1
                        .byte $b1, $b1, $b1, $b1, $b1, $b1, $b1, $b1
                        .byte $b1, $b1, $b1, $b1, $b1, $b1, $b1, $b1
                        .byte $b1, $b1, $b1, $b1, $b1, $b1, $b1, $b1
                        .byte $b1, $b1, $b1, $b1, $b1, $b1, $b1, $b1
                        .byte $b1, $b1, $b1, $b1, $b1, $b1, $b1, $b1
                        .byte $b1, $b1, $b1, $b1, $b1, $b1, $b1, $b1
                        .byte $b1, $b1, $b1, $b1, $b1, $b1, $b1, $b1
                        .byte $b1, $b1, $b1, $b1, $b1, $b1, $b1, $b1
                        .byte $b1, $b1, $b1, $b1, $b1, $b1, $b1, $b1
                        .byte $b1, $b1, $b1, $b1, $b1, $b1, $b1, $b1
                        .byte $b1, $b1, $b1, $b1, $b1, $b1, $b1, $b1
                        .byte $b1, $b1, $b1, $b1, $b1, $b1, $b1, $b1
                        .byte $b1, $b1, $b1, $b1, $b1, $b1, $b1, $b1
                        .byte $b1, $b1, $b1, $b1, $b1, $b1, $b1, $b1
                        .byte $b1, $b1, $b1, $b1, $b1, $b1, $b1, $b1
                        .byte $b1, $b1, $b1, $b1, $b1, $b1, $b1, $b1
                        .byte $b1, $b1, $b1, $b1, $b1, $b1, $b1, $b1
                        .byte $b1, $b1, $b1, $b1, $b1, $b1, $b1, $b1
                        .byte $b1, $b1, $b1, $b1, $b1, $b1, $b1, $b1
                        .byte $b1, $b1, $b1, $b1, $b1, $b1, $b1, $b1
                        .byte $b1, $b1, $b1, $b1, $b1, $b1, $b1, $b1
                        .byte $b1, $b1, $b1, $b1, $b1, $b1, $b1, $b1
                        .byte $b1, $b1, $b1, $b1, $b1, $b1, $b1, $b1
                        .byte $b1, $b1, $b1, $b1, $b1, $b1, $b1, $b1
                        .byte $b1, $b1, $b1, $b1, $b1, $b1, $b1, $b1
                        .byte $b1, $b1, $b1, $b1, $b1, $b1, $b1, $b1
                        .byte $b1, $b1, $b1, $b1, $b1, $b1, $b1, $b1
                        .byte $b1, $b1, $b1, $b1, $b1, $b1, $b1, $b1
                        .byte $b1, $b1, $b1, $b1, $b1, $b1, $b1, $b1
                        .byte $b1, $b1, $b1, $b1, $b1, $b1, $b1, $b1
                        .byte $b1, $b1, $b1, $b1, $b1, $b1, $b1, $b1
                        .byte $b1, $b1, $b1, $b1, $b1, $b1, $b1, $b1
                        .byte $b1, $b1, $b1, $b1, $b1, $b1, $b1, $b1
                        .byte $b1, $b1, $b1, $b1, $b1, $b1, $b1, $b1
                        .byte $b1, $b1, $b1, $b1, $b1, $b1, $b1, $b1
                        .byte $b1, $b1, $b1, $b1, $b1, $b1, $b1, $b1
                        .byte $b1, $b1, $b1, $b1, $b1, $b1, $b1, $b1
                        .byte $b1, $b1, $b1, $b1, $b1, $b1, $b1, $b1
                        .byte $b1, $b1, $b1, $b1, $b1, $b1, $b1, $b1
                        .byte $b1, $b1, $b1, $b1, $b1, $b1, $b1, $b1
                        .byte $b1, $b1, $b1, $b1, $b1, $b1, $b1, $b1
                        .byte $b1, $b1, $b1, $b1, $b1, $b1, $b1, $b1
                        .byte $b1, $b1, $b1, $b1, $b1, $b1, $b1, $b1
                        .byte $b1, $b1, $b1, $b1, $b1, $b1, $b1, $b1
                        .byte $b1, $b1, $b1, $b1, $b1, $b1, $b1, $b1
                        .byte $b1, $b1, $b1, $b1, $b1, $b1, $b1, $b1
                        .byte $b1, $b1, $b1, $b1, $b1, $b1, $b1, $b1
                        .byte $b1, $b1, $b1, $b1, $b1, $b1, $b1, $b1
                        .byte $b1, $b1, $b1, $b1, $b1, $b1, $b1, $b1
                        .byte $b1, $b1, $b1, $b1, $b1, $b1, $b1, $b1
                        .byte $b1, $b1, $b1, $b1, $b1, $b1, $b1, $b1
                        .byte $b1, $b1, $b1, $b1, $b1, $b1, $b1, $b1
                        .byte $b1, $b1, $b1, $b1, $b1, $b1, $b1, $b1
                        .byte $b1, $b1, $b1, $b1, $b1, $b1, $b1, $b1
                        .byte $b1, $b1, $b1, $b1, $b1, $b1, $b1, $b1
                        .byte $b1, $b1, $b1, $b1, $b1, $b1, $b1, $b1
                        .byte $b1, $b1, $b1, $b1, $b1, $b1, $b1, $b1
                        .byte $b1, $b1, $b1, $b1, $b1, $b1, $b1, $b1
                        .byte $b1, $b1, $b1, $b1, $b1, $b1, $b1, $b1
                        .byte $b1, $b1, $b1, $b1, $b1, $b1, $b1, $b1
                        .byte $b1, $b1, $b1, $b1, $b1, $b1, $b1, $b1
                        .byte $b1, $b1, $b1, $b1, $b1, $b1, $b1, $b1
                        .byte $b1, $b1, $b1, $b1, $b1, $b1, $b1, $b1
                        .byte $b1, $b1, $b1, $b1, $b1, $b1, $b1, $b1
                        .byte $b1, $b1, $b1, $b1, $b1, $b1, $b1, $b1
                        .byte $b1, $b1, $b1, $b1, $b1, $b1, $b1, $b1
                        .byte $b1, $b1, $b1, $b1, $b1, $b1, $b1, $b1
                        .byte $b1, $b1, $b1, $b1, $b1, $b1, $b1, $b1
                        .byte $b1, $b1, $b1, $b1, $b1, $b1, $b1, $b1
                        .byte $b1, $b1, $b1, $b1, $b1, $b1, $b1, $b1
                        .byte $b1, $b1, $b1, $b1, $b1, $b1, $b1, $b1
                        .byte $b1, $b1, $b1, $b1, $b1, $b1, $b1, $b1
                        
                        .byte $b1, $b1, $b1, $b1, $b1, $b1, $b1, $b1
                        .byte $b1, $b1, $b1, $b1, $b1, $b1, $b1, $b1
                        .byte $b1, $b1, $b1, $b1, $b1, $b1, $b1, $b1
                        .byte $b1, $b1, $b1, $b1, $b1, $b1, $b1, $b1
                        .byte $b1, $b1, $b1, $b1, $b1, $b1, $b1, $b1
                        .byte $b1, $b1, $b1, $b1, $b1, $b1, $b1, $b1
                        .byte $b1, $b1, $b1, $b1, $b1, $b1, $b1, $b1
                        .byte $b1, $b1, $b1, $b1, $b1, $b1, $b1, $b1
                        .byte $b1, $b1, $b1, $b1, $b1, $b1, $b1, $b1
                        .byte $b1, $b1, $b1, $b1, $b1, $b1, $b1, $b1
                        .byte $b1, $b1, $b1, $b1, $b1, $b1, $b1, $b1
                        .byte $b1, $b1, $b1, $b1, $b1, $b1, $b1, $b1
                        .byte $b1, $b1, $b1, $b1, $b1, $b1, $b1, $b1
                        .byte $b1, $b1, $b1, $b1, $b1, $b1, $b1, $b1
                        .byte $b1, $b1, $b1, $b1, $b1, $b1, $b1, $b1
                        .byte $b1, $b1, $b1, $b1, $b1, $b1, $b1, $b1
                        .byte $b1, $b1, $b1, $b1, $b1, $b1, $b1, $b1
                        .byte $b1, $b1, $b1, $b1, $b1, $b1, $b1, $b1
                        .byte $b1, $b1, $b1, $b1, $b1, $b1, $b1, $b1
                        .byte $b1, $b1, $b1, $b1, $b1, $b1, $b1, $b1
                        .byte $b1, $b1, $b1, $b1, $b1, $b1, $b1, $b1
                        .byte $b1, $b1, $b1, $b1, $b1, $b1, $b1, $b1
                        .byte $b1, $b1, $b1, $b1, $b1, $b1, $b1, $b1
                        .byte $50, $40, $50, $40, $50, $40, $50, $40
                        .byte $50, $50, $50, $50, $50, $50, $50, $50
                        
                        .byte $fe, $b4, $b5, $b6, $b7
                        
waitkey                 lda $CB
                        cmp #$40
                        beq waitkey
                        lda #$37
                        sta $01
                        jmp $FCE2

                        *= $5f40
colorforeground         .byte 2
                        .byte $b
                        .byte 1
colorram                .byte 1
colorbackground         .byte 0
                        
